# normal convention with spring cloud config server is to use port 8888
server:
  port: 8899

spring:
  application:
    name: spring-cloud-config-server
  profiles:
    active: default
  cloud:
    config.server.git.uri: file://C:/Users/Haripr/git/spring-cloud-config-repo
#    below key can also be used to toggle discovery client, moving to config first
#    discovery.enabled: true
