# normal convention with spring cloud config server is to use port 8888
server:
  port: 8888

spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config.server.git.uri: file:\\C:\Users\Haripr\git\spring-cloud-config-repo
#    below key can also be used to toggle discovery client
#    discovery.enabled: true

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka