# normal convention with spring cloud config server is to use port 8888
server:
  port: 8899

spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config.server.git.uri: https://github.com/hariprasath-r/spring-cloud-config-repo.git
#    below key can also be used to toggle discovery client
    discovery.enabled: true

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: ${spring.application.name}
    # registers with ip address instead of hostname
    preferIpAddress: false