# normal convention with spring cloud config server is to use port 8888
server:
  port: 8899

spring:
  cloud:
    config.server:
      git:
        uri: file://C:/Users/Haripr/git/spring-cloud-config-repo
        clone-on-start: true
#        search-paths: local
#    below key can also be used to toggle discovery client, moving to config first
#    discovery.enabled: true
